### ISSUE TITLE
Allow tapes to have a TTL

### ISSUE THREAD

**Issue by robfletcher** [betamaxteam/betamax#10]
If a tape has a TTL then recorded interactions should be discarded & re-recorded once the TTL expires.

**Comment by cowboygneox** [comment]
@robfletcher since this is a testing framework that is largely used to ensure that developers are meeting their own assumed API, this sounds like a really bad idea to one day have the tape just die and attempt to make a new recording. I would suggest that there is an option that a Betamax test could occasionally verify that the assumed contract is still true by reacquiring the data and comparing to the tape, but I don't see a timebomb like TTL ever being ok. Please feel free to open this and provide comments so that I may better understand your ask, assuming it still is an ask.
