### ISSUE TITLE
Tape not being created

### ISSUE THREAD

**Issue by michaelrice** [betamaxteam/betamax#146]
I have a grails 2.1.1 app. It uses [yavijava/yavijava](https://github.com/yavijava/yavijava) and uses apache httpclient. This app communicates to a SOAP api over https. When I write a test the test passes but there is no tape being created. I have uploaded the sample grails app here [michaelrice/vcbeta](https://github.com/michaelrice/vcbeta). Could you please let me know what I am doing wrong to get this working?

In the grails project I have included the yavijava jar built using 1.7.0_67

Thanks

**Comment by cowboygneox** [comment]
@michaelrice First off, we are very willing to help, but an issue for troubleshooting the library is best communicated via our new Gitter page (which did not exist when this was posted, so don't worry about it).

Second, from the looks of it, it appears that the HTTPClient you're using isn't being fully configured. Did you try adding in the `BetamaxRoutePlanner.configure(client)` noted in http://betamax.software/#proxy-compatibility?

I'm going to close this, since it doesn't appear to be an issue with the product, but please do use our Gitter page to ask any and all questions you might have. @tdespenza you too!
