### ISSUE TITLE
Set custom match rules

### ISSUE THREAD

**Issue by mmazi** [betamaxteam/betamax#158]
The `match` property of `@Betamax` should probably be declared as `MatchRule[]` instead of `MatchRules[]`. This, together with #159, completely prevents the user from using custom rules.

(This is about the code in the current HEAD of the master branch.)

**Comment by cowboygneox** [comment]
@mmazi Is this still an issue? I thought I fixed this...

**Comment by mmazi** [comment]
@cowboygneox , thanks for getting back on this. I don't know if this is still an issue. This prevented me from using the current version of Betamax at the time, and resorted to other solutions. I don't work on the project where this happened any more though.

**Comment by cowboygneox** [comment]
@mmazi I'm going to close this. This will certainly be covered in the new release.

**Comment by jessestuart** [comment]
@cowboygneox Hey there! Unless I'm missing something, it seems there's still no (relatively easy) way to implement custom instances of `MatchRule`, since (as @mmazi points out) the `match` property of `@Betamax` is of type `MatchRules[]`, as reflected [on master](https://github.com/betamaxteam/betamax/blob/master/betamax-junit/src/main/java/software/betamax/junit/Betamax.java).

Thoughts?
