### ISSUE TITLE
Make `Recorder` a TestRule if possible

### ISSUE THREAD

**Issue by pledbrook** [betamaxteam/betamax#176]
The `Recorder` class currently implements `MethodRule` which means it can't be used with `@ClassRule`. If there is no reason that the recorder can't be set to run for the duration of the test case (not just each individual test), then `Recorder` should implement `TestRule` instead (which can be used for both `@Before`/`@After` and `@BeforeClass`/`@AfterClass`).

**Comment by cowboygneox** [comment]
@pledbrook I don't see any reason we can't have **both** right? Since the proxy is expensive to launch, but loading the tape is cheap, I would actually like to see a time when we launch the proxy per test class/file or maybe per JVM. I think that removing `MethodRule` will be part of that goal. Is this a blocker for the short term, or is this more of a feature request?

**Comment by pledbrook** [comment]
I can still run the proxy per test, so it's not a blocker. Not sure what you're referring to by having "both", but `TestRule` means you can use per test or per class. Per JVM is independent of rules probably, although I'm not certain. That's something that probably needs to be configured at the build level.

**Comment by pledbrook** [comment]
I've just noticed that `RecorderRule` in _master_ does implement `TestRule`. I only looked at the _1.1.2_ tag before raising this issue. I can close this or leave it open to track the per-VM feature request.

**Comment by cowboygneox** [comment]
@pledbrook I'm glad you looked. That must've been something that @robfletcher did and I didn't notice. Let's close this.
