### ISSUE TITLE
Simulate faults like delays, connection refused, ...

### ISSUE THREAD

**Issue by mirelon** [betamaxteam/betamax#177]
Something like http://wiremock.org/simulating-faults.html

**Comment by pledbrook** [comment]
I don't speak for the core developers, but I consider this a significant expansion of scope for Betamax. The library would have to introduce some way of effectively defining mock behaviour. I'd prefer Betamax to interoperate with Wiremock and MockServer rather than duplicate their behaviour.

One possible option is to treat the underlying LittleProxy implementation as a pluggable platform for which someone could add mock response behaviour, leaving it out of core. Could be a significant amount of work though, and again, an expansion of scope. Chaining proxies in the tests may be just as effective.

**Comment by cowboygneox** [comment]
@pledbrook The configuration concept was supposed to provide that, but I still think we're a ways from it. I think we're still a pretty far ways out from implementing anything like Wiremock, especially when Wiremock already does it.

**Comment by cowboygneox** [comment]
I think that recording the time it took to round trip to the server (thus making it editable) will cover a lot of cases. The only thing Betamax is not well equipped for are any connection-based exception; Betamax only supports responses from the server. Making those responses be 4XX or 5XX is as easy as editing the tape, though. I will make a feature request for recording the duration, but as for connection break simulations, that will take a lot more thought.

**Comment by cowboygneox** [comment]
Delays are covered in #183 and https://trello.com/c/C8nsdJIx. Connection faults can happen with Betamax off or by tweaking the (future) delay to be something absurd.
