### ISSUE TITLE
Use ProxyConfiguration by default

### ISSUE THREAD

**Issue by mirelon** [betamaxteam/betamax#179]
Here: https://github.com/betamaxteam/betamax/blob/master/betamax-core/src/main/java/software/betamax/Recorder.java#L38

is the default creation of Recorder. The Configuration, which is built, is not added as a listener. I propose that the ProxyConfiguration should be used here as a default. Then users are not required to explicitly specify ProxyConfiguration. (otherwise they spend log time debugging why the tape is not created)

**Comment by cowboygneox** [comment]
I will consider this today. I think you're right.

**Comment by cowboygneox** [comment]
@mirelon I agree that the proxy should be the default, but I don't think this is the fix we want. I already am not a fan of the `Configuration` path we're going down, mostly because it implies that we can replace it with some other configuration, which is not true. I think we need to step up and consider a change to the `Configuration` idea altogether. My initial thought is to have something like a `ProxyRecorderRule` instead, and then having a simple constructor of overrides.

I'm also not much of a fan of the builder pattern, but since Java doesn't allow us to use default parameters (seriously?), we don't have much of choice.

@mirelon what do you think? You've obviously dug in a bit and probably have some insight?

**Comment by mirelon** [comment]
I have the same thoughts, but I would do all of this under the hood (do not put this burder on the user). The user want to see only `new Recorder` and if he wants to customize it, then he will look for the other constructor. So in the meantime I would place the ProxyConfiguration there (for the 2.0 snapshots).

As for the builder pattern - I would consider Scala with optional named parameters and more concise syntax.

**Comment by pledbrook** [comment]
Did this fix go into the alpha-1 release? It seems that the `http.proxyPort` property isn't being set unless I initialise the recorder rule with an explicit `ProxyConfiguration` like so:

    @Rule RecorderRule recorder = new RecorderRule(ProxyConfiguration.builder().build())
