### ISSUE TITLE
TapeMode doesn't have any effect

### ISSUE THREAD

**Issue by nilskuhn** [betamaxteam/betamax#232]
Seems so that TapeMode doesn't have any effect in version 2 :(

Whether we set `software.betamax.TapeMode.READ_WRITE` as default via `software.betamax.Configuration.builder().defaultMode(TapeMode.READ_WRITE)` or per test via annotation `@Betamax(tape="no_steps_devServer01_160810_A7_4D", mode=TapeMode.READ_WRITE)`: The tests ignore existing tapes and request the resource with each test execution.

Problems occur in this grails application: https://github.com/iteratec/OsmDetailAnalysis
We use betamax from here: https://repo.grails.org/grails/core/software/betamax/betamax-junit/2.0.1/

**Comment by cowboygneox** [comment]
I'm pretty sure that I have many tests that assert that `@Betamax` uses the TapeMode. It's a known issue that the configuration builder doesn't respect it. Can you check again?

**Comment by leonard84** [comment]
@nilskuhn what happens if you set it to `TapeMode.READ_ONLY` does it work then, or does it say that it can't find the correct recording/fail with tape is not writeable? My guess would be that the request do not match, you might need to change the `matchRules` the default is `MatchRules.method, MatchRules.uri` however you seem to want to compare the query too.

Does it work in `WptDetailDataDefaultStrategyTest` but not in `FetchJobFailTest` ?

**Comment by nilskuhn** [comment]
Thanks for the hints. I'll give it a try asap.

**Comment by nilskuhn** [comment]
We removed betamax from the project because it was easier for us to mock our service call making the http request without a capture/replay library. So I can't test that anymore.
Shame on me that I didn't response since february :(
